write-manifest:
    rsconnect write-manifest notebook --overwrite notebook.ipynb

deploy:
    rsconnect deploy notebook \
        --title "02 - Chicago Food Inspections - Data Validation" \
        notebook.ipynb
